### ISSUE TITLE
Platform - Landing page

### ISSUE THREAD

**Issue by marnovo** [src-d/backlog#651]
User story: *As a prospective user, I want to see information about the repository matching tool and have means to log in, so that I understand the working and benefits before I try it and am able to do so once I want to.*

Requirements:
- Refer to UI: You can find the UI for the landing/login here:
https://app.zeplin.io/project.html#pid=58d294980a92b762343c43e1&sid=58f60e1c1046322b6b6e37fb (updated)
Also updated the elements sheet with the CTA button:
https://app.zeplin.io/project.html#pid=58d294980a92b762343c43e1&sid=58d29b0c7baa0c77d80b65d1 (updated)

.
- [ ] Navbar behavior similar behavior to current sourced.tech one
  - [ ] Initial/top state: transparent background
  - [ ] Scrolled down state: displays solid background color with slight shadow similar to shown in: https://app.zeplin.io/project.html#pid=58d294980a92b762343c43e1&sid=58d29b0a7baa0c77d80b6365
- [ ] Page resizing behavior:
  - [ ] When page width is too narrow for showing the side-by-side text/images in the 2 explanative steps , the images will be below the text, since they're larger, as ordered below. <img width="540" alt="screen shot 2017-04-19 at 12 39 01 pm" src="https://cloud.githubusercontent.com/assets/15906764/25176171/95f9fa7e-24fd-11e7-9a1a-3dbee2aecdb8.png">
  - [ ] When page width is too narrow for showing the side-by-side text/images in the 3 How it works steps , the images will be above the text, since they are smaller, and each step will be above the next.
- [ ] **NavBar**
  - [ ] source{d} logo links to the very same page
  - [ ] NavBar `HOME` links to the very same page
  - [ ] NavBar `LEARN MORE` links to the /about/ page
  - [ ] NavBar `SEND FEEDBACK` links to the form as detailed in #656.
  - [ ] NavBar `LOGIN / JOIN` takes the user to the GitHub login/registration as detailed in #652
- [ ] **Top CTA/hero banner**
  - [ ] Button `[Get Started with GitHub]` takes the user to the GitHub login/registration as detailed in #652
  - [ ] Text link `LEARN MORE` under the CTA button links to the /about/ page
- [ ] **How it Works**
  - [ ] Text link `LEARN MORE` under the `How it Works` session links to the /about/ page
- [ ] **Bottom CTA**
  - [ ] Button `[Get Started with GitHub]` in the bottom takes the user to the GitHub login/registration as detailed in #652
- [ ] **Footer**
  - [ ] Company
    - [ ] Text link `About Us` links to http://sourced.tech/
    - [ ] Text link `Manifesto` links to http://sourced.tech/manifesto/
    - [ ] Text link `Roadmap` links to http://blog.sourced.tech/post/our-roadmap/
    - [ ] Text link `Team` links to http://sourced.tech/team/
    - [ ] Text link `Stack` links to http://sourced.tech/stack/
    - [ ] Text link `Careers` links to http://sourced.tech/careers/
  - [ ] Community
    - [ ] Text link `Tech Talks` links to http://talks.sourced.tech/
    - [ ] Text link `Open Source` links to https://github.com/src-d
    - [ ] Text link `Open Data` links to https://data.world/vmarkovtsev/
    - [ ] Text link `Blog` links to http://blog.sourced.tech/post/our-roadmap/
  - [ ] Networks
    - [ ] Text link `Twitter` links to https://twitter.com/srcd_
    - [ ] Text link `GitHub` links to https://twitter.com/srcd_
    - [ ] Text link `Medium` links to https://medium.com/source-d
    - [ ] Text link `AngelList` links to https://angel.co/source-d
    - [ ] Text link `LinkedIn` links to https://www.linkedin.com/company-beta/10284920/
  - [ ] Contact
    - [ ]  Text link `Claudio Coello 16 2º Izq 28001 – Madrid, Spain` links to https://www.google.es/maps/place/source%7Bd%7D/@40.4223316,-3.6889377,17z/data=!3m1!4b1!4m5!3m4!1s0xd422899933066a7:0x15da344c018f6dd0!8m2!3d40.4223275!4d-3.686749?
Text link `Roadmap` links to http://blog.sourced.tech/post/our-roadmap/
    - [ ] Text link `hello@sourced.tech` links to `mailto:hello@sourced.tech`
    - [ ] Text link `talent@sourced.tech` links to `mailto:talent@sourced.tech`
- [ ] User behavior tracking as per #658

**Comment by Serabe** [comment]
I guess this is superseded by #682, isn't it?
